import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: // hoge
Readonly<{
  children: React.ReactNode
  // hoge: React.ReactNode,
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <>{children}</>
        {/* <>{hoge}</> */}
      </body>
    </html>
  )
}
